backend:
  name: git-gateway
  branch: master
  auth_scope: repo  # Requerido para Auth0
  repo: "tu-usuario/tu-repositorio"  # Ej: "nachoalonso/mi-galeria-fotos"

# Configuración de Auth0
local_backend: true  # Opcional: Para desarrollo local
publish_mode: editorial_workflow  # Opcional: Si quieres borradores

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Gallery Items"
    folder: "src/gallery"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "photoDate", label: "Date", widget: "datetime" }
      - { name: "credit", label: "Photo Credit", widget: "string" }
      - { name: "linkToAuthor", label: "Author Link", widget: "string" }
      - { name: "src", label: "Image File", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "imgDir", label: "Images Directory", widget: "hidden", default: "./src/images/" }