backend:
  name: git-gateway
  branch: main # Tu rama principal

media_folder: "src/images" # Carpeta donde se guardarán las imágenes
public_folder: "/images"  # Ruta pública

collections:
  - name: "gallery"
    label: "Gallery Items"
    folder: "src/gallery"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "photoDate", label: "Date", widget: "datetime" }
      - { name: "credit", label: "Photo Credit", widget: "string" }
      - { name: "linkToAuthor", label: "Author Link", widget: "string" }
      - { name: "src", label: "Image File", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "imgDir", label: "Images Directory", widget: "hidden", default: "./src/images/" }